image: ruby:2.4.0

clone:
  depth: 3  

pipelines:
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
            - apt-get update
            - apt-get install -y build-essential libpq-dev nodejs
            - bundle install
            - bundle exec rake db:test:prepare
            - bundle exec rake db:migrate RAILS_ENV=test 
            - bundle exec rspec
          services:
            - postgres
          deployment:
            test

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: pipelines
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password